### PR TITLE
Use new ansibleUtils singleton functions

### PR DESCRIPTION
**Pull request by nre-ableton**
- Ignore entire .ansible directory for ansible-lint
- Update python-utils to 0.13
- Use venv.inside instead of multiple venv.run calls
- Use new ansibleUtils singleton functions

### CODE REVIEW

**Comment by nre-ableton** [comment]
@Ableton/devtools please have a look at this canary PR. Once merged, I'll make similar PRs for our other roles.

BTW, once this is finished, it means we can _finally_ run CI jobs on third-party forks for these repositories.

**Review by mst-ableton — APPROVED** [review]
wow, looks pretty awesome! lgtm

**Review by rco-ableton — APPROVED** [review]
Nice!

**Review by ala-ableton — APPROVED** [review]
Very nice!

**Comment by nre-ableton** [comment]
@ablbot rebase

**Pull request merged**
