### PR TITLE
Fix linting issues

### PR DESCRIPTION
**Pull request by staticdev**
I had a couple issues trying to run ansible-lint and molecule locally direct from a clone and install dependencies, that are fixed in this PR.

Namely:

1. ansible lint does not find role declared in converge:

   ```
   % ansible-lint
   WARNING  Skipped installing collection dependencies due to running in offline mode.
   WARNING  Listing 1 violation(s) that are fatal
   syntax-check[specific]: the role 'ansible-role-nix' was not found in /home/user/workspace/ansible-role-nix/molecule   /default/roles:/home/user/.cache/ansible-compat/1a0050/roles:/home/user/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/user/workspace/ansible-role-nix/molecule/default
   molecule/default/converge.yml:10:7
   ```

1. docker-py fails running molecule with (check https://github.com/docker/docker-py/issues/3113):

   ```
   Error while fetching server API version: request() got an unexpected keyword argument 'chunked'
   ```

   Adding a restriction to urllib3 solves the issue.

1. errors pointed by `molecule/default/coverage.yml` are also fixed, so the file does not need to be ignored anymore.

### CODE REVIEW

**Comment by nre-ableton** [comment]
@ablbot runci

**Review by nre-ableton — COMMENTED** [review]
Hi there! :wave: Thanks for the PR. :+1: The actual changes LGTM, but there are some other issues that need to be resolved.

First, before we get to the technical issues, our company requires a [CLA to be digitally signed](https://ableton.github.io/cla/) by any external contributors. Just to be clear, all personal information is protected under the GDPR, since Ableton is based in Germany and the data isn't added to any customer mailing lists or anything like that. It's only stored by our legal team. Also, you only need to sign the CLA once, then you can submit as many PRs as you like to any of our repos. :slightly_smiling_face: 

---

Ok, as for the technical stuff... so unfortunately CI failed (sorry, you won't be able to see the results page since the Jenkins server is firewalled off to the outside world), but basically the error is:

```
ERROR! the role 'ableton.nix' was not found in /home/nre/Code/Ableton/ansible-role-nix/molecule/default/roles:/home/nre/.cache/ansible-compat/1a0050/roles:/home/nre/.cache/molecule/ansible-role-nix/default/roles:/home/nre/Code/Ableton:/home/nre/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/nre/Code/Ableton/ansible-role-nix/molecule/default

The error appears to be in '/home/nre/Code/Ableton/ansible-role-nix/molecule/default/converge.yml': line 10, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - ableton.nix
      ^ here
```

I can also reproduce this locally when checking out your PR branch and running `molecule test` locally. However, when I run `molecule test` locally I don't have any problems. Likewise, I don't have the issue with `docker-py` that you mentioned, but I don't mind pinning the package to work around a known issue. How exactly are you running molecule?

As for the ansible-lint changes, thanks, I don't remember why we excluded the `molecule` converge playbook, but IIRC it had to do with a bug in some old ansible-lint version.

I think the easiest way to proceed with this PR would be to drop the change from `ansible-role-nix` to `ableton.nix` and just merge the linter fixes. Then we can figure out how to change the role name. I agree that it would be better to use the canonical role name for molecule, since this resembles how you'd use this role in actual playbooks, but we've struggled to find a solution that satisfies molecule, developer workstations, CI, and other scenarios. This has been a problem since Ansible changed their role name requirements.

**Comment by staticdev** [comment]
@nre-ableton no problem, CLA signed. Regarding the `molecule, developer workstations, CI, and other scenarios` I have created a dozen Ansible roles that work everywhere following this approach, you can also see an example:
https://github.com/staticdev/ansible-role-python-developer/blob/main/molecule/default/converge.yml#L23
Also the most popular roles on Ansible Galaxy follow thist approach:
https://github.com/geerlingguy/ansible-role-docker/blob/master/molecule/default/converge.yml#L24

One thing I could do is check maybe what problem you have on Jenkins (if you send a Jenkinsfile) or on workstation and I can also try to help.

**Comment by nre-ableton** [comment]
> One thing I could do is check maybe what problem you have on Jenkins (if you send a Jenkinsfile) or on workstation and I can also try to help.

The root of the problem is we have is that our Jenkins nodes don't check out repositories with unique names. It's unfortunately a bit of a difficult problem to fix. Basically, when "normal people" clone the repository, it gets cloned to `ansible-role-nix`, and the `ansible-compat` tools anticipate this by basically copying the role to `~/.cache/ansible-compat/<hash>` and set `ANSIBLE_ROLES_PATH` accordingly.

However, our CI nodes must check out all repositories to a directory named `/jenkins/workspace`, for reasons that aren't worth going into here but is not something we can change just for the benefit of these Ansible roles. The problem is that `ansible-compat` calculates the above [hash very naively](https://github.com/ansible/ansible-compat/blob/442748f6de7a63f85b4b1d3abd24c001260b271a/src/ansible_compat/prerun.py#L15) by using current directory basename. This means that all CI jobs for Ansible roles on our CI system use `workspace` as the cache key, which inevitably clashes with other roles or dependencies from `ansible-galaxy` etc.

Although it should theoretically be possible to override this with `ANSIBLE_ROLES_PATH` or `ANSIBLE_COLLECTIONS_PATH`, it's not. I've filed bug reports with varying degrees of success in both [molecule](https://github.com/ansible-community/molecule/issues/3663) and [ansible-lint](https://github.com/ansible/ansible-lint/issues/2683) about this to try to get them to work around the behavior.

Currently, we work around this by manually creating a symlink in `~/.cache/ansible-compat` to "fool" these tools, but it's a bit of a hack. I have a few ideas for workarounds that I have been meaning to test, but I haven't had the time recently. Since I've been doing more Ansible role stuff this week, I'll give it a try and hopefully come up with a solution. Let me get back to you on this...

**Comment by staticdev** [comment]
No problem, there is nothing critical in this PR anyway. I wait as much as needed.

**Comment by staticdev** [comment]
@nre-ableton I am sorry I used github sync branch functionality and it actually does merge instead of rebase.

**Comment by nre-ableton** [comment]
Ok, the code changes look fine, but can you squash all commits so there's only a single one? Thanks. 👍

**Comment by staticdev** [comment]
@nre-ableton hope it is correct now ;)

**Review by nre-ableton — APPROVED** [review]
Looks great, thanks! 👍 I'll run it through CI, just to make sure, but I don't anticipate any problems.

**Comment by nre-ableton** [comment]
@ablbot runci

**Comment by nre-ableton** [comment]
CI failed due to a race condition that occurs when setting up the Ansible role symlink. I need to make another fix to our systems before this job can build. 😅

**Comment by nre-ableton** [comment]
@ablbot runci

**Comment by nre-ableton** [comment]
@staticdev Ok, finally passing CI. 😌 Thanks again for your contribution! 👍

**Pull request merged**
