### PR TITLE
Use XDG_CONFIG_HOME only if running as nix user

### PR DESCRIPTION
**Pull request by nre-ableton**
Fixes https://github.com/Ableton/ansible-role-nix/issues/146

### CODE REVIEW

**Comment by nre-ableton** [comment]
@staticdev Is there any way that you can test this PR in your GitHub Action and confirm that it works?

**Comment by staticdev** [comment]
@nre-ableton I am not aware of a way since it is not on Ansible Galaxy. An option would be to release as `0.0.8-alpha.1` so that I can put my playbook to point to it.

**Comment by nre-ableton** [comment]
> @nre-ableton I am not aware of a way since it is not on Ansible Galaxy. An option would be to release as `0.0.8-alpha.1` so that I can put my playbook to point to it.

I'm not sure what the implications would be of pushing another tag to this repository. I don't want to trigger a bunch of renovate updates for people. But I think I know of another way -- I forked this repo and merged this branch into my fork's main, and then published that role on Galaxy: https://galaxy.ansible.com/nre_ableton/nix.

So you should be able to try it out with `nre_ableton.nix` instead. Let me know if it works!

**Comment by staticdev** [comment]
@nre-ableton tested, it works! https://github.com/staticdev/nix-playbook/actions/runs/5637162111/job/15269969960

**Comment by nre-ableton** [comment]
@staticdev Great, thanks for taking the time to test it!

@ala-ableton Ok, this PR is ready for review.

**Comment by staticdev** [comment]
Thanks a lot @nre-ableton! I already tested also the 0.0.8.. Btw I got to know Ableton, by this role.. I love music =)

**Pull request merged**
